swagger:
  base: "example.demo"
  enable: true
  title: "this ia a title"
  description: "this is a description"
  version: "this is a version"
  contract:
    name: "name"
    url: "https://www.springboot.com"
    email: "1170015014@qq.com"

