spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-commit-interval: 100
      max-poll-records: 500
      fetch-max-wait-ms: 500
      fetch-min-size: 1
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      linger-ms: 1
      max-block-ms: 5000
      max-inflight-requests-per-connection: 5
      max-request-size: 1048576
      compression-type: gzip
      request-timeout-ms: 30000
      metadata-max-age-ms: 300000
      max-poll-records: 500
      fetch-max-wait-ms: 500
      fetch-min-size: 1