spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    tokenPrefix: "token:"
    tokenExpire: 12
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0