spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    primary:
      url: jdbc:postgresql://localhost:5432/public?useSSL=false&serverTimezone=UTC
      username: postgres
      password: 123456
      driver-class-name: org.postgresql.Driver
      hikari:
        max-lifetime: 1800000  # 连接最大寿命 30min
        connection-timeout: 1800000  # 连接超时时间 30min
        minimum-idle: 100   # 最小空闲连接数
        maximum-pool-size: 200  # 最大连接池大小
        connection-test-query: "select 1"
        idle-timeout: 600000 # 空闲连接超时时长 10min
    secondary:
      url: jdbc:mysql://localhost:3306/public?useSSL=false&serverTimezone=UTC
      username: ENC(2dwq/1A3Izar5AxsXgp+uRKmyBN4NWkK)
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        max-lifetime: 1800000  # 连接最大寿命 30min
        connection-timeout: 1800000  # 连接超时时间 30min
        minimum-idle: 100   # 最小空闲连接数
        maximum-pool-size: 200  # 最大连接池大小
        connection-test-query: "select 1"
        idle-timeout: 600000 # 空闲连接超时时长 10min
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        format-sql: true
  redis:
    host: localhost
    port: 6379
    database: 0
sso:
  enable: true
  SECRET_KEY: your-secret-key-123456
  JWT_EXPIRATION: 86400000
  REDIS_PREFIX: "sso:token:"
  white-list:
    - /api/v1/auth/login
    - /api/v1/white-list/**

mybatis-plus:
  # MyBatis-Plus配置只对secondary数据源生效
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
jwt:
  secret: your-secret-key-here-should-be-very-long-and-secure
  expiration: 86400000  # 24 hours in milliseconds
  header: Authorization
  token-prefix: "Bearer "
jasypt:
  encryptor:
    password: your_grace
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator

# 代理配置
http:
  port: 8080
  proxy:
    host: proxy.example.com
