name: flutter_ui_demo
description: A Flutter application demonstrating various UI components.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_syntax_view: ^4.0.0
  flutter_slidable: ^3.0.0
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/ 