server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-username/springcloud-config
          default-label: main
          search-paths: '{application}'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 